
SELECT WEEK, SUM(DIE)
FROM accident
GROUP BY WEEK;

SELECT AREA1, SUM(DIE)
FROM accident
GROUP BY AREA1;

SELECT AREA1, AREA2, SUM(DIE)
FROM accident
GROUP BY AREA1, AREA2;

SELECT KIND, COUNT(*)
FROM accident
GROUP BY KIND
ORDER BY COUNT(*) DESC
LIMIT 0,5;

SELECT WEEK, COUNT(*)
FROM accident
GROUP BY WEEK
ORDER BY COUNT(*)
LIMIT 0,1;



SELECT E.ename, E.deptno, D.dname
FROM emp E, dept D
WHERE E.deptno=D.deptno;

SELECT *
FROM emp E, dept D
WHERE E.deptno=D.deptno;

SELECT E.comm, E.sal, D.loc
FROM emp E, dept D
WHERE E.deptno=D.deptno
AND E.comm IS NOT NULL;

SELECT SUM(E.sal), D.dname
FROM emp E, dept D
WHERE D.loc IN('new york','dallas')
AND E.deptno=D.deptno
GROUP BY D.dname;


CREATE TABLE IT_MEMBER (
 NUM INT
 , NAME VARCHAR(10)
 , COURSE_NO INT
);
INSERT INTO IT_MEMBER VALUES (1, 'AA', 1);
INSERT INTO IT_MEMBER VALUES (2, 'BB', 1);
INSERT INTO IT_MEMBER VALUES (3, 'CC', 2);
INSERT INTO IT_MEMBER VALUES (4, 'DD', 2);
INSERT INTO IT_MEMBER VALUES (5, 'EE', 4);
INSERT INTO IT_MEMBER VALUES (6, 'FF', NULL);

CREATE TABLE COURSE02 (
 COURSE_NO INT
 , COURSE_NAME VARCHAR(20)
);
INSERT INTO COURSE02 VALUES (1, 'DIGITAL');
INSERT INTO COURSE02 VALUES (2, 'BIG DATA');
INSERT INTO COURSE02 VALUES (3, 'CLOUD');
INSERT INTO COURSE02 VALUES (4, 'NFC');

COMMIT;


SELECT I.NUM, I.NAME, I.COURSE_NO, C.COURSE_NAME
FROM it_member I LEFT OUTER JOIN course02 C
ON I.COURSE_NO=C.COURSE_NO;

SELECT I.NUM, I.NAME, C.COURSE_NO, C.COURSE_NAME
FROM it_member I RIGHT OUTER JOIN course02 C
ON I.COURSE_NO=C.COURSE_NO;












